language: java
jdk:
- oraclejdk14
addons:
  sonarcloud:
    organization: "kilya"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ikondratev_test-java-maven